//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AmazonWebScraperTests {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class TestFixtures {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TestFixtures() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AmazonWebScraperTests.TestFixtures", typeof(TestFixtures).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///&lt;!doctype html&gt;&lt;html lang=&quot;en-gb&quot; class=&quot;a-no-js&quot; data-19ax5a9jf=&quot;dingo&quot;&gt;&lt;!-- sp:feature:head-start --&gt;
        ///&lt;head&gt;&lt;script&gt;var aPageStart = (new Date()).getTime();&lt;/script&gt;&lt;meta charset=&quot;utf-8&quot;/&gt;
        ///
        ///&lt;script type=&apos;text/javascript&apos;&gt;var ue_t0=ue_t0||+new Date();&lt;/script&gt;
        ///&lt;!-- sp:feature:cs-optimization --&gt;
        ///&lt;meta http-equiv=&apos;x-dns-prefetch-control&apos; content=&apos;on&apos;&gt;
        ///&lt;link rel=&quot;dns-prefetch&quot; href=&quot;https://images-eu.ssl-images-amazon.com&quot;&gt;
        ///&lt;link rel=&quot;dns-prefetch&quot; href=&quot;https://m.media-amazon.com&quot;&gt;
        ///&lt;link rel=&quot;dns- [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Amazon_Headphone_Html {
            get {
                return ResourceManager.GetString("Amazon_Headphone_Html", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;div data-asin=&quot;B098QSLZNQ&quot; data-index=&quot;0&quot; data-uuid=&quot;71e95303-fa82-4913-b85a-5fac30b5731b&quot; data-component-type=&quot;s-search-result&quot; class=&quot;sg-col-4-of-12 s-result-item s-asin sg-col-4-of-16 AdHolder sg-col sg-col-4-of-20&quot; data-component-id=&quot;58&quot; data-cel-widget=&quot;search_result_0&quot;&gt;
        ///    &lt;div class=&quot;sg-col-inner&quot;&gt;
        ///
        ///
        ///
        ///        &lt;span cel_widget_id=&quot;MAIN-SEARCH_RESULTS-0&quot; class=&quot;celwidget slot=MAIN template=SEARCH_RESULTS widgetId=search-results_1&quot; data-csa-c-id=&quot;7d3din-ov8dgg-br1902-wjfvgu&quot; data-cel-widget=&quot;MAIN [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Amazon_Headphone_Product_Html {
            get {
                return ResourceManager.GetString("Amazon_Headphone_Product_Html", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;div class=&quot;s-main-slot s-result-list s-search-results sg-row&quot;&gt;
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///    &lt;div data-asin=&quot;B098QSLZNQ&quot; data-index=&quot;0&quot; data-uuid=&quot;71e95303-fa82-4913-b85a-5fac30b5731b&quot; data-component-type=&quot;s-search-result&quot; class=&quot;sg-col-4-of-12 s-result-item s-asin sg-col-4-of-16 AdHolder sg-col sg-col-4-of-20&quot; data-component-id=&quot;58&quot; data-cel-widget=&quot;search_result_0&quot;&gt;
        ///        &lt;div class=&quot;sg-col-inner&quot;&gt;
        ///
        ///
        ///
        ///            &lt;span cel_widget_id=&quot;MAIN-SEARCH_RESULTS-0&quot; class=&quot;celwidget slot=MAIN template=SEARCH_RES [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Amazon_Headphone_ProductList_Html {
            get {
                return ResourceManager.GetString("Amazon_Headphone_ProductList_Html", resourceCulture);
            }
        }
    }
}
